FROM golang:1-alpine AS build

RUN apk add git libusb-dev

COPY . /go/src/github.jpl.nasa.gov/bdube/golab
WORKDIR /go/src/github.jpl.nasa.gov/bdube/golab
COPY . /go/src/github.jpl.nasa.gov/bdube/golab
RUN pwd && ls
RUN go build -o /bin/golab/multiserver-linux-amd64 ./cmd/multiserver/*.go

